In [2]:
import requests

def get_market_cap(stock_code):
    if stock_code.startswith("6"):
        secid = f"1.{stock_code}"
    else:
        secid = f"0.{stock_code}"
    
    url = f"https://push2.eastmoney.com/api/qt/stock/get?secid={secid}&fields=f116,f117"
    headers = {
        'User-Agent': 'Mozilla/5.0'
    }
    
    try:
        resp = requests.get(url, headers=headers)
        data = resp.json()
        total_mv = data['data']['f116']  # 总市值
        circulation_mv = data['data']['f117']  # 流通市值
        return total_mv, circulation_mv
    except Exception as e:
        return None, None

# 示例
print(get_market_cap("600519"))  # 贵州茅台
print(get_market_cap("000001"))  # 平安银行

(1967130382932.0, 1967130382932.0)
(216958165453.63998, 216954293283.0)

In [1]:
import pandas as pd

# 假设你已经读取了90天K线数据为df
df = pd.read_csv('股票K线数据_90天.csv', parse_dates=['日期'], dtype={'股票代码': str}) 
df['股票代码'] = df['股票代码'].astype(str).str.replace(r'^[01]\.', '', regex=True)
df['股票代码'] = df['股票代码'].astype(str).str.ljust(6, "0")
stock_codes = df['股票代码'].astype(str).unique().tolist()

In [3]:
import requests
import time

def get_market_cap(stock_code):
    if stock_code.startswith('6'):
        secid = f'1.{stock_code}'
    else:
        secid = f'0.{stock_code}'

    url = f'https://push2.eastmoney.com/api/qt/stock/get?secid={secid}&fields=f116,f117'
    headers = {
        'User-Agent': 'Mozilla/5.0'
    }

    try:
        resp = requests.get(url, headers=headers, timeout=5)
        data = resp.json()
        total_mv = data['data']['f116']  # 总市值
        circ_mv = data['data']['f117']  # 流通市值
        return stock_code, total_mv, circ_mv
    except:
        return stock_code, None, None

In [4]:
market_caps = []
for code in stock_codes:
    stock_code, total_mv, circ_mv = get_market_cap(code)
    market_caps.append({
        '股票代码': stock_code,
        '总市值': total_mv,
        '流通市值': circ_mv
    })

market_df = pd.DataFrame(market_caps)
market_df.to_csv('market_cap_info.csv', index=False, encoding='utf-8-sig')

In [7]:
market_df

        股票代码           总市值          流通市值
0     001300  2.981379e+09  8.098594e+08
1     002631  3.826958e+09  3.809147e+09
2     601798  2.538422e+09  2.538422e+09
3     603928  2.723011e+09  2.723011e+09
4     002584  5.302061e+09  3.918371e+09
...      ...           ...           ...
5179  300117  3.082068e+08  3.082068e+08
5180  300051  2.313695e+09  2.274451e+09
5181  300022  4.107138e+09  4.107047e+09
5182  002200  1.060605e+09  1.060605e+09
5183  000040  7.285682e+08  5.167530e+08

[5184 rows x 3 columns]